language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --omit=*.virtualenvs*,*virtualenv* manage.py test
after_success:
  coveralls
