language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo fc-cache
  - coverage run --omit=*.virtualenvs*,*virtualenv* manage.py test
after_success:
  coveralls
